cache:
  paths:
  - node_modules
  - .cache

stages:
- deploy to gitlab

deploy to gitlab:
  stage: deploy to gitlab
  script:
    - yarn
    - yarn lint
    - yarn build
    - ls
    - rm -rf /etc/gitlab-runner/GatsbyBlog && mkdir /etc/gitlab-runner/GatsbyBlog
    - cp -r public/* /etc/gitlab-runner/GatsbyBlog
    - echo '部署到gitlab上成功'
  environment:
    name: gitlab
    url: https://blog.towavephone.com
    on_stop: stop deploy on gitlab

stop deploy on gitlab:
  stage: deploy to gitlab
  script: rm -rf /etc/gitlab-runner/GatsbyBlog
  when: manual
  environment:
    name: gitlab
    action: stop